before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

nfpms:
  - maintainer: Vitoru <contact@vitoru.dev>
    formats:
      - deb
      - rpm

changelog:
  sort: asc
